### ISSUE TITLE
What happen if we have 10000 children

### ISSUE THREAD

**Issue by RyugaRyuzaki** [MrLightful/shadcn-tree-view#7]
Hi, i have a type here 
```
/**
 *
 */
export interface IModelTree {
  type: string;
  expressID: number;
  elementIdMap: ElementIdMap;
  checked: boolean;
  children: IModelTree[];
}```
So what happen with performance if i have 10000 elements, each element has 10000 child anf 5 grades like that? Many thank

**Comment by MrLightful** [comment]
Hi @RyugaRyuzaki,

The component hasn't been stress-tested. Can't say much, but I guess it won't be pretty.

A good thing is that the component won't insert all items into the DOM tree until the node is expanded. So it won't attempt to render all items at once in DOM. This is good.

Although 1000 children on the same level is a problem. There are packages that try to avoid rendering items, unless they are in the view. I guess that would be the direction you should follow. So the items that the user doesn't see are not in the DOM tree. Right now, they would be.

Anyways, good luck with your project!

**Comment by RyugaRyuzaki** [comment]
So @mui/treeview is beeter than this?

**Comment by MrLightful** [comment]
There are no explicit benefits in `@mui/treeview`, taking into account your context. The same limitations and recommendations apply: load and render only children you intend to show and/or in viewport.

**Comment by RyugaRyuzaki** [comment]
> There are no explicit benefits in `@mui/treeview`, taking into account your context. The same limitations and recommendations apply: load and render only children you intend to show and/or in viewport.
So this library can not design for load only once. I mean we can check if each child just render oly once time when we click expand

**Comment by RyugaRyuzaki** [comment]
This [function](https://github.com/MrLightful/shadcn-tree-view/blob/main/src/tree-view.tsx#L72-L89) is long task. What if we have a parent 1000 children and 1000 grandchildren, how we can increase performance?

**Comment by RyugaRyuzaki** [comment]
@MrLightful i solved by using memo My own new engine - Test performance visibility and colorize
https://youtu.be/hY_JoFwgjmI
